2022-03-15 12:47:35,543 server.py  DEBUG      server               Была вызвана функция config_load c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-03-15 12:47:35,551 server.py  DEBUG      server               Аргументы загружены успешно  
2022-03-15 12:47:35,552 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами ('7777', '192.168.56.1'), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-03-15 12:47:35,604 core.py    INFO       core                 Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: 192.168.56.1. Если адрес не указан, принимаются соединения с любых адресов.  
2022-03-15 12:47:42,799 core.py    INFO       core                 Установлено соедение с ПК ('192.168.56.1', 59225)  
2022-03-15 12:47:43,301 core.py    DEBUG      core                 Разбор сообщения от клиента : {'action': 'presence', 'time': 1647341262.8135378, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtI0PF3i+nv+3kdDSinu9\nXIsg5BlIcElRdfq8g5ySdHMcMVE7K4gaxS21A8Gkr8JpYH2lgnMJ/vL3pceeHKA1\nnSl1DOGgj1mOd4RgXGHxnP1vdfAg7cAOWC1w0D0bjbCIbadluMXT07rNlyMmAVmx\n8Iz+75+23idoB+G07wT5aYoI/LbyP63GOCI79I49MIa9DlnNLJXR3uF5GUrd7UJR\nxLn23jR23ZIAmN5Pri8o8XmSwJc0d/WVal2HnqD7A1RrVR1ClvsJyLKJ6bBBmL5b\naazp0kmtzxKbPhjuMLECjnnJ10Qm1ILqCoGaXcFuzYGJ2X1KNI+LgRih6hBPQ9BU\nTQIDAQAB\n-----END PUBLIC KEY-----'}}  
2022-03-15 12:47:43,301 core.py    DEBUG      core                 Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtI0PF3i+nv+3kdDSinu9\nXIsg5BlIcElRdfq8g5ySdHMcMVE7K4gaxS21A8Gkr8JpYH2lgnMJ/vL3pceeHKA1\nnSl1DOGgj1mOd4RgXGHxnP1vdfAg7cAOWC1w0D0bjbCIbadluMXT07rNlyMmAVmx\n8Iz+75+23idoB+G07wT5aYoI/LbyP63GOCI79I49MIa9DlnNLJXR3uF5GUrd7UJR\nxLn23jR23ZIAmN5Pri8o8XmSwJc0d/WVal2HnqD7A1RrVR1ClvsJyLKJ6bBBmL5b\naazp0kmtzxKbPhjuMLECjnnJ10Qm1ILqCoGaXcFuzYGJ2X1KNI+LgRih6hBPQ9BU\nTQIDAQAB\n-----END PUBLIC KEY-----'}  
2022-03-15 12:47:43,309 core.py    DEBUG      core                 Correct username, starting passwd check.  
2022-03-15 12:47:43,311 core.py    DEBUG      core                 Auth message = {'response': 511, 'bin': '63e433189961c9a2d9237e85bc38e13f8306839425ccd4bf88e2cdf0298d2a5616d8fe4f99194dfbca2740331a99840ff4d2d2d58871ca5f7d606afc81f30a65'}  
2022-03-15 12:47:43,833 core.py    DEBUG      core                 Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647341263.313353, 'account_name': 'test1'}  
2022-03-15 12:47:44,340 core.py    DEBUG      core                 Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647341263.8628836, 'user': 'test1'}  
2022-03-15 12:47:45,887 utils.py   DEBUG      utils                get_message err: timed out  
2022-03-15 12:47:46,848 core.py    DEBUG      core                 Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647341266.4956527, 'account_name': 'test2'}  
2022-03-15 12:47:51,853 core.py    DEBUG      core                 Разбор сообщения от клиента : {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1647341271.4025993, 'mess_text': 'UZ//4bHePWDUtb4jV7HXl5bHOTVsR6pfOZU8vciOCXBdfu/to/HDvJb8Inha9yYbqqQ0nq710jAF89lu195MGccObaieGV6pKUuWfiwDwm7qxdVCh0Z1UCNLGHP7d7Sme8bxssty4t9PjWB2xItyK9gHowDGoVdN9PERY8S0h8wOt8kl9pTW4hibrwUGQMvK2xJ8s7LaGFchqko8Qp4rtR986rWK9ZxIcZxn4kWAgvEctEutd/iewjIU+W6LHC8S2zJHobOiZTeorH14MtwiKP/McqHPkY2OPcR/bVE0acl8iqLRwEVLLddLF29hMCEYqRTmpI+BvEcHxV72rkiwHQ=='}  
2022-03-15 12:47:57,857 core.py    DEBUG      core                 Разбор сообщения от клиента : {'action': 'exit', 'time': 1647341277.4658237, 'account_name': 'test1'}  
2022-03-15 12:47:57,857 core.py    INFO       core                 Клиент ('192.168.56.1', 59225) отключился от сервера.  
2022-03-15 21:16:01,376 server.py  DEBUG      server               Была вызвана функция main c параметрами (), {}.Вызов из модуля __main__.Вызов из функции <module>.Вызов из функции <module>  
2022-03-15 23:24:45,334 server_pr.py DEBUG      server_pr            Была вызвана функция config_load c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-03-15 23:24:45,334 server_pr.py DEBUG      server_pr            Аргументы загружены успешно  
2022-03-15 23:24:45,334 server_pr.py DEBUG      server_pr            Была вызвана функция arg_parser c параметрами ('7777', '192.168.56.1'), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-03-15 23:26:12,252 server_pr.py DEBUG      server_pr            Была вызвана функция config_load c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-03-15 23:26:12,252 server_pr.py DEBUG      server_pr            Аргументы загружены успешно  
2022-03-15 23:26:12,252 server_pr.py DEBUG      server_pr            Была вызвана функция arg_parser c параметрами ('7777', '192.168.56.1'), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-03-15 23:26:12,283 core.py    INFO       core                 Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: 192.168.56.1. Если адрес не указан, принимаются соединения с любых адресов.  
2022-03-15 23:26:14,709 server_pr.py DEBUG      server_pr            Была вызвана функция main c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>  
